In [1]:
import numpy as np

In [3]:
p = 2
n = 3
d = 5

In [13]:
ranks = np.random.randint(5, size=5).reshape(1, 5)
print(ranks)
values = np.arange(5).reshape(5, 1)
mask = ranks > values
mask

[[3 3 0 3 4]]


array([[ True,  True, False,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True, False,  True,  True],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

In [20]:
b[0][mask]

array([ 0,  1,  3,  4,  5,  6,  8,  9, 10, 11, 13, 14, 19])

In [22]:
b = np.arange(75).reshape(3, 5, 5)

In [33]:
mask

array([[ True,  True, False,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True, False,  True,  True],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

In [30]:
b[:, mask]

array([[ 0,  1,  3,  4,  5,  6,  8,  9, 10, 11, 13, 14, 19],
       [25, 26, 28, 29, 30, 31, 33, 34, 35, 36, 38, 39, 44],
       [50, 51, 53, 54, 55, 56, 58, 59, 60, 61, 63, 64, 69]])

In [46]:
b = np.arange(15).reshape(3, 5) + 0.01
foo = np.zeros((3, 5))
np.reciprocal(b, where=b > 4, out=foo)
foo

/var/folders/gn/ng_hj_cn5v350ryftn566_6w0000gq/T/ipykernel_83331/527317638.py:3: RuntimeWarning: invalid value encountered in reciprocal
  np.reciprocal(b, where=b > 4, out=foo)


array([[0.        , 0.        , 0.        , 0.        , 0.24937656],
       [0.1996008 , 0.16638935, 0.14265335, 0.12484395, 0.11098779],
       [0.0999001 , 0.09082652, 0.08326395, 0.07686395, 0.07137759]])

In [34]:
from collections import namedtuple

In [47]:
foo

array([[0.        , 0.        , 0.        , 0.        , 0.24937656],
       [0.1996008 , 0.16638935, 0.14265335, 0.12484395, 0.11098779],
       [0.0999001 , 0.09082652, 0.08326395, 0.07686395, 0.07137759]])

In [35]:
Color = namedtuple("Color", ["red", "green", "blue"])

In [37]:
red = Color(red=255, green=0, blue=0)

In [38]:
red._fields

('red', 'green', 'blue')

In [27]:
mask[None, :, :].shape

(1, 5, 5)

In [28]:
b[mask[None, :, :]]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 1

In [6]:
(np.random.randn(n, d) @ np.random.randn(p, d, d)).shape

(2, 3, 5)

In [5]:
np.arange(24).reshape(2, 3, 4).T.shape

(4, 3, 2)

In [16]:
x = np.arange(10).reshape(1, 2, 5)
y = np.ones(2)
x, y

(array([[[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]]),
 array([1., 1.]))

In [15]:
np.einsum("i n d, n -> d", x, y)

array([ 5.,  7.,  9., 11., 13.])